@startuml

title __COMPONENTS's Class Diagram__\n

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      namespace components {
        class no.ntnu.idi.apollo69.game_engine.components.BoosterComponent {
            {static} + MAPPER : ComponentMapper<BoosterComponent>
            + boost : float
            + defaultValue : float
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      namespace components {
        class no.ntnu.idi.apollo69.game_engine.components.BoundingCircleComponent {
            {static} + MAPPER : ComponentMapper<BoundingCircleComponent>
            + circle : Circle
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      namespace components {
        class no.ntnu.idi.apollo69.game_engine.components.PlayableComponent {
            {static} + MAPPER : ComponentMapper<PlayableComponent>
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      namespace components {
        class no.ntnu.idi.apollo69.game_engine.components.PositionComponent {
            {static} + MAPPER : ComponentMapper<PositionComponent>
            + position : Vector2
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      namespace components {
        class no.ntnu.idi.apollo69.game_engine.components.RotationComponent {
            {static} + MAPPER : ComponentMapper<RotationComponent>
            + degrees : float
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      namespace components {
        class no.ntnu.idi.apollo69.game_engine.components.VelocityComponent {
            {static} + MAPPER : ComponentMapper<VelocityComponent>
            + idle : float
            + scalar : float
            + velocity : Vector2
        }
      }
    }
  }
  

  no.ntnu.idi.apollo69.game_engine.components.BoosterComponent .up.|> com.badlogic.ashley.core.Component
  no.ntnu.idi.apollo69.game_engine.components.BoundingCircleComponent .up.|> com.badlogic.ashley.core.Component
  no.ntnu.idi.apollo69.game_engine.components.PlayableComponent .up.|> com.badlogic.ashley.core.Component
  no.ntnu.idi.apollo69.game_engine.components.PositionComponent .up.|> com.badlogic.ashley.core.Component
  no.ntnu.idi.apollo69.game_engine.components.RotationComponent .up.|> com.badlogic.ashley.core.Component
  no.ntnu.idi.apollo69.game_engine.components.VelocityComponent .up.|> com.badlogic.ashley.core.Component


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
