@startuml

    namespace no.ntnu.idi.apollo69.Apollo69 {
        class Apollo69 {
            - deviceId : String
            + Apollo69()
            + Apollo69()
            + create()
            + dispose()
            + render()
        }
        class Device {
            {static} + DEVICE_ID : String
            {static} + NAME : String
        }
        interface Variables {
            {static} + buttonHeight : float
            {static} + buttonWidth : float
            {static} + fontScale : float
            {static} + nicknameHeight : float
            {static} + spacing : float
            {static} + textExit : String
            {static} + textExitGame : String
            {static} + textJoin : String
            {static} + textPlay : String
            {static} + textSettings : String
        }

        namespace controller {
            class GameController {
                + GameController()
                + boostButtonPressed()
                + boostButtonReleased()
                + shootButtonPressed()
                + shootButtonReleased()
                + touchpadMoved()
            }
            class LobbyController {
                + LobbyController()
                + exitButtonPressed()
                + joinButtonPressed()
            }
            class MainMenuController {
                + MainMenuController()
                + playButtonPressed()
            }
            class MatchmakingController {
                + MatchmakingController()
                + cancelMatchmaking()
                + onMatchmakingDone()
                + onShow()
                + startMatchmaking()
            }
        }

        namespace model {
            class GameModel {
                - HEIGHT : float
                - SCREEN_HEIGHT : float
                - SCREEN_WIDTH : float
                - WIDTH : float
                - camera : OrthographicCamera
                - textButtons : HashMap<String, TextButton>
                + GameModel()
                + addTextButton()
                + getCamera()
                + getGameEngine()
                + getTextButton()
                + moveCameraToSpaceship()
                + navigateToLobby()
                + renderBackground()
                + renderBoundary()
                + renderNetworkBatch()
                + renderNetworkShapes()
                - renderAsteroids()
                - renderExplosions()
                - renderHealthBar()
                - renderPickups()
                - renderPowerups()
                - renderShieldBar()
                - renderSpaceships()
                {static} - sortByValue()
                - trim()
                - updatePlayerScores()
            }
            class MatchmakingModel {
                - connecting : boolean
                - connectingFailed : boolean
                - matchmakingDone : boolean
                - matchmakingListener : Listener
                - positionInQueue : int
                - queueSize : int
                + MatchmakingModel()
                + dispose()
                + getPositionInQueue()
                + getQueueSize()
                + isConnected()
                + isConnecting()
                + isConnectingFailed()
                + isMatchmakingDone()
                + setConnecting()
                + setConnectingFailed()
                + setMatchmakingDone()
                + setPositionInQueue()
                + setQueueSize()
            }
            class ServerUpdateListener {
                + received()
                ~ ServerUpdateListener()
            }
            class LobbyModel {
            }
            class MainMenuModel {
            }
        }

        namespace navigation {
            class Navigator {
                - screen : Screen
                + changeScreen()
                + dispose()
                + getScreen()
                - setScreen()
            }
            enum ScreenType {
                GAME
                LOBBY
                MAIN_MENU
                MATCHMAKING
                SETTINGS
            }
        }

        namespace network {
              class GameClient {
                  - client : Client
                  {static} - clientConnecting : boolean
                  - serverIp : String
                  - tcpPort : int
                  - udpPort : int
                  + GameClient()
                  + connectClient()
                  + disconnectClient()
                  + getGameState()
                  {static} + isClientConnecting()
                  + isConnected()
                  + sendMessage()
                  + setGameState()
              }
              class NetworkClientSingleton {
                  - client : Client
                  - defaultServerHost : String
                  {static} - networkClientSingleton : NetworkClientSingleton
                  - tcpPort : int
                  - udpPort : int
                  + getClient()
                  + getGameClient()
                  {static} + getInstance()
                  + getTcpPort()
                  + getUdpPort()
                  - NetworkClientSingleton()
                  - getHost()
              }
        }

        namespace view {
            class GameView {
                - shapeRenderer : ShapeRenderer
                - spriteBatch : SpriteBatch
                - stage : Stage
                + GameView()
                + hide()
                + render()
                + show()
            }
            class LobbyView {
                - backgroundTexture : Texture
                - spriteBatch : SpriteBatch
                - stage : Stage
                - themeMusic : Music
                + LobbyView()
                + dispose()
                + hide()
                + pause()
                + render()
                + resize()
                + resume()
                + show()
                - getFakeHighScoreList()
            }
            class MainMenuView {
                - backgroundTexture : Texture
                - spriteBatch : SpriteBatch
                - stage : Stage
                + MainMenuView()
                + dispose()
                + hide()
                + pause()
                + render()
                + resize()
                + resume()
                + show()
            }
            class MatchmakingView {
                - bitmapFont : BitmapFont
                - spriteBatch : SpriteBatch
                - stage : Stage
                + MatchmakingView()
                + dispose()
                + hide()
                + pause()
                + render()
                + resize()
                + resume()
                + show()
                - handleInput()
            }
        }

        namespace game_engine {
            class Assets {
                {static} - COMBINED_ATLAS : String
                {static} - EXPLOSIONS_ATLAS : String
                {static} - FONT : String
            }
            class Background {
              - backgroundObjects : ArrayList<BackgroundObject>
              + Background()
              + render()
            }
            class BackgroundObject {
                - bounds : Vector2
                - position : Vector3
                - texture : Texture
                ~ BackgroundObject()
            }
            class GameEngine {
                - engine : Engine
                - gameOver : boolean
                - returningToLobby : boolean
                - timeAccumulator : float
                + GameEngine()
                + dispose()
                + getEngine()
                + getPlayer()
                + getPlayerControlSystem()
                + isGameOver()
                + isReturningToLobby()
                + setGameOver()
                + update()
            }
            class GameEngineFactory {
                - GAME_UPDATE_SECONDS : float
                - NETWORK_UPDATE_SECONDS : float
                + create()
            }

            namespace components {
                class BoosterComponent {
                    {static} + MAPPER : ComponentMapper<BoosterComponent>
                    + boost : float
                    + defaultValue : float
                }
                class BoundingCircleComponent {
                    {static} + MAPPER : ComponentMapper<BoundingCircleComponent>
                    + circle : Circle
                }
                class PlayableComponent {
                    {static} + MAPPER : ComponentMapper<PlayableComponent>
                }
                class PositionComponent {
                    {static} + MAPPER : ComponentMapper<PositionComponent>
                    + position : Vector2
                }
                class RotationComponent {
                    {static} + MAPPER : ComponentMapper<RotationComponent>
                    + degrees : float
                }
                class VelocityComponent {
                    {static} + MAPPER : ComponentMapper<VelocityComponent>
                    + idle : float
                    + scalar : float
                    + velocity : Vector2
                }
            }

            namespace entities {
                class SpaceshipFactory {
                    + create()
                    + createPlayableSpaceship()
                }
            }

            namespace entity_systems {
                class BoundsSystem {
                    - entities : ImmutableArray<Entity>
                    + addedToEngine()
                    + update()
                }
                interface InputHandlerInterface {
                    {abstract} + boost()
                    {abstract} + move()
                    {abstract} + shoot()
                }
                class MovementSystem {
                    - entities : ImmutableArray<Entity>
                    + addedToEngine()
                    + update()
                }
                class PlayerControlSystem {
                    - player : Entity
                    + PlayerControlSystem()
                    + boost()
                    + move()
                    + shoot()
                }
                class SendPositionSystem {
                    - interval : float
                    - player : Entity
                    - timeAccumulator : float
                    + SendPositionSystem()
                    + addedToEngine()
                    + update()
                }
                class UpdateGameStateSystem {
                    - interval : float
                    - players : ImmutableArray<Entity>
                    - timeAccumulator : float
                    + UpdateGameStateSystem()
                    + addedToEngine()
                    + update()
                    - parseGameState()
                }
            }
        }

    }

@enduml