@startuml

title __ENTITY_FACTORIES's Class Diagram__\n

  namespace no.ntnu.idi.apollo69server {
    namespace game_engine {
      namespace entity_factories {
        class no.ntnu.idi.apollo69server.game_engine.entity_factories.AsteroidFactory {
            - BASE_SPEED : int
            - DAMAGE_OF_ASTEROID : float
            - HP_OF_ASTEROID : float
            - MAX_EXTRA_SPEED : int
            + create()
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69server {
    namespace game_engine {
      namespace entity_factories {
        class no.ntnu.idi.apollo69server.game_engine.entity_factories.ExplosionFactory {
            {static} + create()
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69server {
    namespace game_engine {
      namespace entity_factories {
        class no.ntnu.idi.apollo69server.game_engine.entity_factories.GemFactory {
            + create()
            - createCoinGem()
            - createMeteoriteGem()
            - createRubyGem()
            - createStarGem()
            - generalCreate()
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69server {
    namespace game_engine {
      namespace entity_factories {
        class no.ntnu.idi.apollo69server.game_engine.entity_factories.PowerupFactory {
            + createRandomPowerup()
            - create()
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69server {
    namespace game_engine {
      namespace entity_factories {
        class no.ntnu.idi.apollo69server.game_engine.entity_factories.ShotFactory {
            + create()
        }
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69server {
    namespace game_engine {
      namespace entity_factories {
        class no.ntnu.idi.apollo69server.game_engine.entity_factories.SpaceshipFactory {
            + create()
            - getSpaceShipId()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
