@startuml

title __GAME_ENGINE's Class Diagram__\n

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      class no.ntnu.idi.apollo69.game_engine.Assets {
          {static} - ASTEROID_ATLAS : String
          {static} - COMBINED_ATLAS : String
          {static} - EXPLOSIONS_ATLAS : String
          {static} - GAME_ATLAS : String
          {static} - GEMS_ATLAS : String
          {static} - INVISIBLE_ATLAS : String
          {static} - LASER : String
          {static} - MUSIC : Class<Music>
          {static} - POWERUPS_ATLAS : String
          {static} - SKIN : Class<Skin>
          {static} - SOUND : Class<Sound>
          {static} - TEXTURE_ATLAS : Class<TextureAtlas>
          {static} - THEME : String
          {static} - UI_SKIN : String
          {static} - assetManager : AssetManager
          {static} - bigFont : BitmapFont
          {static} - bigGenerator : FreeTypeFontGenerator
          {static} - bigParameter : FreeTypeFontParameter
          {static} - smallFont : BitmapFont
          {static} - smallGenerator : FreeTypeFontGenerator
          {static} - smallParameter : FreeTypeFontParameter
          {static} - textureCache : ObjectMap<String, AtlasRegion>
          {static} - yellowFont : BitmapFont
          {static} - yellowGenerator : FreeTypeFontGenerator
          {static} - yellowParameter : FreeTypeFontParameter
          {static} + getAsteroidRegion()
          {static} + getBackgroundMusic()
          {static} + getBigFont()
          {static} + getBoostedSpaceshipRegion()
          {static} + getExplosionRegion()
          {static} + getGameAtlas()
          {static} + getLaserSound()
          {static} + getPickupRegion()
          {static} + getPowerupRegion()
          {static} + getSmallFont()
          {static} + getSpaceshipRegion()
          {static} + getUiSkin()
          {static} + getYellowFont()
          {static} + load()
          {static} - getRegion()
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      class no.ntnu.idi.apollo69.game_engine.Background {
          - backgroundObjects : ArrayList<BackgroundObject>
          + Background()
          + render()
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      class no.ntnu.idi.apollo69.game_engine.Background.BackgroundObject {
          - bounds : Vector2
          - position : Vector3
          - texture : Texture
          ~ BackgroundObject()
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      class no.ntnu.idi.apollo69.game_engine.GameEngine {
          - engine : Engine
          - gameOver : boolean
          - returningToLobby : boolean
          - timeAccumulator : float
          + GameEngine()
          + dispose()
          + getEngine()
          + getPlayer()
          + getPlayerControlSystem()
          + isGameOver()
          + isReturningToLobby()
          + setGameOver()
          + update()
      }
    }
  }
  

  namespace no.ntnu.idi.apollo69 {
    namespace game_engine {
      class no.ntnu.idi.apollo69.game_engine.GameEngineFactory {
          - GAME_UPDATE_SECONDS : float
          - NETWORK_UPDATE_SECONDS : float
          + create()
      }
    }
  }
  

  no.ntnu.idi.apollo69.game_engine.Background +-down- no.ntnu.idi.apollo69.game_engine.Background.BackgroundObject
  no.ntnu.idi.apollo69.game_engine.GameEngine .up.|> com.badlogic.gdx.utils.Disposable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
